#!/bin/sh

BLANK='#00000000'
CLEAR='#00000088'
DEFAULT='#5294e2ff'   # azul estilo Arc
TEXT='#d3dae3ff'      # texto claro
WRONG='#cc0000ff'
VERIFYING='#5ba32dff'

i3lock \
  --insidever-color=$CLEAR     \
  --ringver-color=$VERIFYING   \
  \
  --insidewrong-color=$CLEAR   \
  --ringwrong-color=$WRONG     \
  \
  --inside-color=$BLANK        \
  --ring-color=$DEFAULT        \
  --line-color=$BLANK          \
  --separator-color=$DEFAULT   \
  \
  --verif-color=$TEXT          \
  --wrong-color=$TEXT          \
  --time-color=$TEXT           \
  --date-color=$TEXT           \
  --layout-color=$TEXT         \
  --keyhl-color=$TEXT          \
  --bshl-color=$WRONG          \
  \
  --screen=1                   \
  --blur=5                     \
  --clock                      \
  --indicator                  \

